stages:
  - fetch
  - build
  - test

fetch-code:
  stage: fetch
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
  script:
    # Clone the repository
    - echo "Cloning the repository..."
    - git clone git@github.com:andreea1987/docker-react.git || { echo "Failed to clone repository"; exit 1; }
    # Check the contents of the current directory
    - echo "Directory contents after cloning:"
    - ls -la
    # Verify and navigate to the cloned directory
    - cd docker-react || { echo "Directory does not exist"; exit 1; }
    - echo "Successfully entered the docker-react directory"

build:
  stage: build
  image: node:16
  cache:
    paths:
      - docker-react/.yarn/cache
  script:
    - cd docker-react
    - yarn install  # Install dependencies
    - yarn build    # Build the project
  artifacts:
    paths:
      - docker-react/build/

test:
  stage: test
  image: node:16
  cache:
    paths:
      - docker-react/.yarn/cache
  script:
    - cd docker-react
    - yarn install
    - yarn test --ci  # Run tests in CI mode


