stages:
  - install
  - test
  - deploy

# Install dependencies
install-dependencies:
  stage: install
  image: node:16
  cache:
    paths:
      - node_modules/
  script:
    - yarn install

# Run tests
run-tests:
  stage: test
  image: node:16
  cache:
    paths:
      - node_modules/
  script:
    - yarn test --watchAll=false

# Deploy to AWS Elastic Beanstalk
deploy:
  stage: deploy
  image: amazon/aws-cli
  script:
    # Install Elastic Beanstalk CLI
    - pip install awsebcli --upgrade --user

    # Configure AWS
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region eu-west-2

    # Initialize the Elastic Beanstalk environment
    - eb init -p node.js "frontend" --region "eu-west-2"

    # Deploy to the specified environment
    - eb deploy "Frontend-env"
  only:
    - master





