stages:
  - install
  - test

install-dependencies:
  stage: install
  image: node:16
  cache:
    paths:
      - node_modules/
  script:
    - yarn install

run-tests:
  stage: test
  image: node:16
  cache:
    paths:
      - node_modules/
  script:
    - yarn test --watchAll=false




