sudo: required
services:
  -docker

before_install:
  - docker build -t abalauca/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true abalauca/docker_react yarn run test -- --coverage