# Use a lightweight Node.js base image
FROM node:lts-alpine

# Set the working directory inside the container
WORKDIR '/app'

# Copy only the package.json and yarn.lock for installing dependencies
COPY package.json yarn.lock ./

# Install Yarn globally
RUN yarn install

# Copy the rest of the application files to the container
COPY . .


# Command to start the application
CMD ["yarn", "run", "start"]